spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 35603378190-n5a7bbg1j9g8uh5l3igm6d66fe7v2k99.apps.googleusercontent.com
            client-secret: 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

  datasource:
#    url: jdbc:postgresql://vigyanshaalaorgdb.ccxfs1ndk8yn.eu-north-1.rds.amazonaws.com:5432/vigyanshaalaDB
#    username: postgres
#    password: Transfer#Ledger
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}


  liquibase:
    enabled: true
    change-log: classpath:db.changelog/changelog.yml


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      enable_lazy_load_no_trans: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: email-smtp.eu-north-1.amazonaws.com
    port: 2587
    username: AKIA4T5JWBQC54RVOCKG
    password: BAo4OHhdeqJCRSwP4B10upbDpPjb3QRGH0DPrwE7BJNA
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 2587
          socketFactory:
            fallback: true
          auth: true
          ssl:
            enable: false
            trust: email-smtp.eu-north-1.amazonaws.com
          starttls:
            enable: false

client-id: "35603378190-n5a7bbg1j9g8uh5l3igm6d66fe7v2k99.apps.googleusercontent.com"
fromEmail: "careers@VigyanShaala.com"
emailDuration: "0 0 20 ? * 1/3"
expiredJob: "0 0 20 ? * SUN"

serverCodePath: "/home/ubuntu/"
jobApplicationsZipPath: "/home/ubuntu/JobApplications/"
